version: "3.8"

services:
  devcontainer:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/workspace:rw
      - ~/.ssh:/home/node/.ssh:ro
      - ~/.aws:/home/node/.aws:ro
    environment:
      - CHOKIDAR_USEPOLLING=true

